stages:
  - build
  - deploy
services:
  - docker:dind
build:
  stage: build
  image: node:latest
  script:
  - npm install
  - npm run build -- --release
  cache:
    paths:
    - build
  artifacts:
    paths:
    - build
  only:
  - master
build_image:
  stage: deploy
  image: docker
  script:
  - "PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$PACKAGE_VERSION" .
  - docker push "$CI_REGISTRY_IMAGE:$PACKAGE_VERSION"
  - docker push "$CI_REGISTRY_IMAGE:latest"
  when: manual
  only:
  - master