stages:
  - build
  - build_image
services:
  - docker:dind
build:
  stage: build
  image: node:latest
  script:
  - npm install
  - npm run build -- --release
  cache:
    paths:
    - build
  artifacts:
    paths:
    - build
  only:
  - master
build_image:
  stage: build_image
  image: docker
  script:
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:v$CI_BUILD_ID" .
  - docker push "$CI_REGISTRY_IMAGE:v$CI_BUILD_ID"
  - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
  - master